import { Folder, Item, ItemType } from '@/types/item';

export const mockFolders: Folder[] = [
  { id: '1', name: 'Personal' },
  { id: '2', name: 'Work' },
  { id: '3', name: 'Finance' },
  { id: '4', name: 'Social' },
];

export const mockItems: Item[] = [
  {
    id: '1',
    name: 'Gmail',
    type: 'login',
    username: 'user@gmail.com',
    password: 'password123',
    folder: '1',
    owner: 'me',
    favorite: false,
    createdAt: Date.now() - 1000000,
    updatedAt: Date.now() - 500000,
  },
  {
    id: '2',
    name: 'GitHub',
    type: 'login',
    username: 'devuser',
    password: 'github2023!',
    folder: '2',
    owner: 'me',
    favorite: true,
    createdAt: Date.now() - 2000000,
    updatedAt: Date.now() - 100000,
  },
  {
    id: '3',
    name: 'Netflix',
    type: 'login',
    username: 'netflix_user',
    password: 'streaming!2023',
    folder: '1',
    owner: 'me',
    favorite: false,
    createdAt: Date.now() - 3000000,
    updatedAt: Date.now() - 300000,
  },
  {
    id: '4',
    name: 'Bank Account',
    type: 'login',
    username: 'bankuser',
    password: 'secure!bank!123',
    folder: '3',
    owner: 'me',
    favorite: true,
    createdAt: Date.now() - 4000000,
    updatedAt: Date.now() - 400000,
  },
  {
    id: '5',
    name: 'Twitter',
    type: 'login',
    username: 'twitterhandle',
    password: 'tweet2023!',
    folder: '4',
    owner: 'me',
    favorite: false,
    createdAt: Date.now() - 5000000,
    updatedAt: Date.now() - 200000,
  },
];